"""initial_schema

Revision ID: 11468eabb117
Revises: 
Create Date: 2026-08-04 18:22:13.085368

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11468eabb117'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nse_symbol', sa.String(length=50), nullable=True),
    sa.Column('bse_code', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cmp', sa.Numeric(precision=12, scale=2), nullable=True, comment='Current Market Price'),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fii_holding_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dii_holding_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('public_holding_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bse_code', name='uq_company_bse_code'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('nse_symbol', name='uq_company_nse_symbol')
    )
    op.create_index(op.f('ix_companies_bse_code'), 'companies', ['bse_code'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_nse_symbol'), 'companies', ['nse_symbol'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False, comment='research | financial | quality | valuation | risk | management | quarterly | summary'),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=True, comment='Fiscal year context'),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_company_agent', 'analysis_cache', ['company_id', 'agent_type'], unique=False)
    op.create_index('ix_analysis_stale', 'analysis_cache', ['is_stale', 'updated_at'], unique=False)
    op.create_table('balance_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('total_assets_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fixed_assets_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_assets_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('inventories_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('receivables_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investments_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('long_term_debt_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_debt_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('current_liabilities_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('trade_payables_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('shareholders_equity_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('share_capital_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('reserves_surplus_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'period_year', 'period_quarter', name='uq_balance_period')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('cfo_cr', sa.Numeric(precision=20, scale=2), nullable=True, comment='Cash Flow from Operations'),
    sa.Column('cfi_cr', sa.Numeric(precision=20, scale=2), nullable=True, comment='Cash Flow from Investing'),
    sa.Column('cff_cr', sa.Numeric(precision=20, scale=2), nullable=True, comment='Cash Flow from Financing'),
    sa.Column('capex_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_change_in_cash_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'period_year', 'period_quarter', name='uq_cashflow_period')
    )
    op.create_table('income_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_quarter', sa.Integer(), nullable=True),
    sa.Column('revenue_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_income_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_income_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('raw_material_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('employee_cost_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_expenses_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_expenses_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('depreciation_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('interest_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pbt_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pat_cr', sa.Numeric(precision=20, scale=2), nullable=True, comment='Profit After Tax'),
    sa.Column('minority_interest_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pat_after_minority_cr', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps_basic', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_per_share', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'period_year', 'period_quarter', name='uq_income_period')
    )
    op.create_index('ix_income_company_period', 'income_statements', ['company_id', 'period_year', 'period_type'], unique=False)
    op.create_table('key_ratios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('roe_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roce_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roa_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ebitda_margin_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_profit_margin_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ev_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('debt_equity_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('asset_turnover', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inventory_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('receivables_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payables_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_conversion_cycle', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_growth_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pat_growth_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('eps_growth_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_type', 'period_year', name='uq_ratio_period')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_watchlist_user_company')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('portfolio')
    op.drop_table('key_ratios')
    op.drop_index('ix_income_company_period', table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_table('cash_flows')
    op.drop_table('balance_sheets')
    op.drop_index('ix_analysis_stale', table_name='analysis_cache')
    op.drop_index('ix_analysis_company_agent', table_name='analysis_cache')
    op.drop_table('analysis_cache')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_nse_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_bse_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
